name: Mediantazy CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Installing dependencies...
      run: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt install git -y
        sudo apt install gcc -y
        sudo apt install cppcheck -y
        sudo apt install doxygen -y
        sudo apt install python3 -y
        cppcheck --help

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v4
    - name: Building
      run: |
        cd ./scripts
        sudo chmod +x ./*.py
        python3 ./build.py build

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v4
    - name: Linting
      run: |
        cd ./scripts
        sudo chmod +x ./*.py
        cppcheck -h
        python3 ./build.py lint
